# Generated by Django 4.1 on 2022-08-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('salary_perhour', models.IntegerField(default=0)),
                ('working_hours', models.IntegerField(default=0)),
                ('total_salry', models.IntegerField(default=0)),
            ],
        ),
    ]
