# Generated by Django 4.1 on 2022-08-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employees_total_salry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='total_salry',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
